project_id = "jmralbctzpdkjvvurach"

[functions.certificate-alerts]
verify_jwt = true

[functions.generate-course-description]
verify_jwt = true

[functions.send-templated-email]
verify_jwt = true

[functions.send-notification]
verify_jwt = true

[functions.workflow-retry]
verify_jwt = true

[functions.translate-with-gemini]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.azure-sso]
verify_jwt = false

[functions.saml-sso]
verify_jwt = false

[functions.sapience-hcm-test]
verify_jwt = true

[functions.import-sapience-employees]
verify_jwt = true
