// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmralbctzpdkjvvurach.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptcmFsYmN0enBka2p2dnVyYWNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3OTA0NjIsImV4cCI6MjA2NzM2NjQ2Mn0.-93uLL2G4fMge-LrpOUkLITPlb8JAa4FBnqz9xsj8gU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});